cmd/gvncli/main.go
The default port in the command line utility was not updated. This PR fixes it.
=> gvncli: update default port

Dockerfile
Adds a simple `Dockerfile`. Result can be tested by pulling the image `guggero/governator`.
=> docker: add default Dockerfile

.travis.yml, Makefile, scripts/install_travis_proto.sh
rpc-check logic copied across from lnd
Add a check for changes in `go.mod`/`go.sum` by running `go mod tidy` and then grepping for go.mod/ go.sum in the output of `git status`. Chose this approach rather than `git describe --dirty` so that the mod check could be run in between the proto install script and proto check without triggering a false positive on potential rpc changes.
=> Makefile: add rpc and go.mod check

accounting/report.go
Add a struct representing a [Harmony](https://github.com/picksco/harmony) accounting record. This struct will form the base of 2 separate PRs (one for off chain accounting, one for on chain), so it is separated out to reduce duplication. I've already written the bulk of the on-chain PR, so I am confident that this struct has the required fields.
=> accounting: add harmony report struct

fiat/coincap_api.go, fiat/coincap_api_test.go, fiat/fiat.go, fiat/fiat_test.go, fiat/prices.go, fiat/prices_test.go
To create accounting reports, we need to individually examine each on chain transaction we have to determine what amounts need to be converted to fiat values. Eg, a channel open needs to be examined to determine whether we paid opening fees or not to determine whether we need to convert that value to fiat or not.
The current fiat api is designed to allow querying of many prices at once, rather than getting of individual price points. To allow us to make a single query to the external price api then get fiat prices as required, we export separate `GetPrice` and `GetData` calls.
=> fiat: export get data and get price functions

cmd/frcli/main.go, cmd/frcli/utils.go, config.go, faraday.go, frdrpc/rpcserver.go, go.mod
To be able to run `faraday` as a library, we need to export some config related elements and create the possibility to instantiate and run the RPC server without it creating its own `grpc.Server` server or REST `proxy.ServeMux` instance.
=> rpcserver+config: prepare to be used as a library

version.go
After https://github.com/lightninglabs/faraday/pull/41 is merged, we should tag a new version.
=> version: bump to 0.2.0-alpha

accounting/on_chain.go
If we do not continue after adding an open channel event, we will
double count our channel open as an on chain payment.
=> bugfix: add continue after adding open channel entry

config.go
Add a version flag to faraday which prints version and exits, as we have in lnd.
Fixes #57
=> config: add version flag

README.md
This PR updates Faraday's readme to include the latest instructions for running with a bitcoin backend, and adds a development section along with some typo fixes and formatting.
=> readme: add chain connection instructions and development section

accounting/config.go, accounting/conversions.go, cmd/frcli/node_report.go, frdrpc/exchange_rate.go, frdrpc/node_report.go, frdrpc/rpcserver.go
This PR makes some small fixes to our node report's fiat:
- Make fiat opt-in on the cli
- Do not set granularity level when fiat is disabled
- Do not set zero value times when fiat is disabled
=> multi: do not get best granularity when fiat is disabled

.travis.yml, itest/Dockerfile
With this PR we first speed up the build by removing the need to download bitcoind every time we change something in our itest folder (this should shave off around 2 minutes of our current itest run). This is achieved by splitting up the docker build into two parts, each with its own base image. For the actual execution we use the ruimarinho/bitcoin-core base image that already contains the bitcoind binary. We use the same image in our testnet cluster environment so it should be fine to use for the integration tests.
We also update to the final version of `lnd v0.11.0` and fix the itest log upload.
=> itest: speed up image build

cmd/frcli/utils.go
With the addition of TLS, the `network` flag is now required to use `frcli` on regtest/testnet. 
Running [without the flag yields](https://github.com/lightninglabs/faraday/issues/67#issuecomment-689232160) `[frcli] open : no such file or directory`, which is quite ambiguous.
This PR wraps the error to more clearly explain what's gone wrong. 
Mentioned in #67
=> frcli: wrap tls cert error with explanation

cmd/frcli/main.go
Fixes https://github.com/lightninglabs/faraday/issues/78.
=> cmd/frcli: add default path for TLS cert

README.md, version.go
This PR updates the Faraday readme to contain an updated introduction (drafted with biz team) and installation instructions. It also bumps the version to `v0.2.1` in preparation for release.
=> Update readme and bump version

README.md
Quick copy fix for the command name for `closereport` on README docs. Noticed this while testing v0.2.1-alpha and reading through the new docs.
=> Fix command name for `closereport` on README docs

frdrpc/macaroons.go, go.mod, go.sum
To make sure we can use the latest version of faraday in LiT, we need to
make sure faraday compiles against the actual v0.11.1 branch of lnd. There
were some conflicting changes to the macaroon service that didn't make
it to the branch that we need to roll back. Those changes don't affect
faraday at all as we were always using the default root key ID anyway.
=> mod+macaroons: bump to lnd v0.11.1-beta.rc3

accounting/entries.go, accounting/entries_test.go
Before: "incoming: 51 mSAT msat outgoing: 51 mSAT msat"
After:  "incoming: 51 mSAT outgoing: 51 mSAT"
=> Remove duplicate msat unit in outputs

frdrpc/node_audit.go, paginater/paginater.go
This PR combines 3 unrelated issues:
- Sort the output of the audit command by timestamp, which has been requested by various users
- Bugfix: the rpc for custom categories switched onchain/offchain categories 
- Paginator: export the function type, because we're using this package in other projects a bit
=> multi: audit labelling bugfix, sort output and export paginator fn

.github/pull_request_template.md, cmd/frcli/node_audit.go, release_notes.md, version.go
This PR combines two small changes for brief review:
1. Now that pool has been released, we can add a pre-set custom category for pool so that pool txns can easily be separated out from regular lnd txns
2. Add in-repo release note tracking, and reminders in comments + PR template
=> multi: add pool category and in-repo release notes

frdrpc/macaroons.go, go.mod, go.sum, release_notes.md
This is mainly necessary as a preparation to bundle the final `lnd v0.12.0-beta` together with Faraday inside of LiT.
=> Bump lnd dependency to v0.12.0-beta.rc3

release_notes.md, version.go
=> version: bump to v0.2.3-alpha

README.md
Link in Readme pointed to `/accounting/docs.md` which takes you to a redirect when it ought to point to `/docs/accounting.md`
=> Update link to accounting documentation

frdrpc/rpcserver.go, release_notes.md
Fixes https://github.com/lightninglabs/faraday/issues/97.
It seems there is a difference in how ALPN is handled between when gRPC
creates the TLS layer and when the golang library does it with
tls.NewListener. To fix the "missing selected ALPN property" error in
node.js and #c clients, we switch over the TLS handling to gRPC.
=> rpcserver: let gRPC handle TLS to avoid ALPN error

accounting/filter.go, accounting/off_chain.go, lndwrap/lndwrap.go
Add some logging and enrich errors used by the accounting report so
that we can debug timeout issues on larger nodes.
=> multi: add detailed errors and more logging

release_notes.md, version.go
Clear release notes and bump version to 0.2.6. Version jumps to
v0.2.6 because we did not bump the version file for v0.2.5, despite
having tagged it.
=> release_notes+version: bump to v0.2.6-alpha

frdrpc/macaroons.go, frdrpc/rpcserver.go
Replaces #127.
In some cases we don't want the default macaroon file to be created on
disk, so we allow passing in a boolean that toggles the macaroon
creation.
This is for the LiT stateless integrated mode.
changes or bugfixes
=> Macaroon stateless

config.go, release_notes.md
Fixes https://github.com/lightninglabs/faraday/issues/141.
The lncfg.CleanAndExpandPath() call was missing for the lnd TLS
certificate path.
changes or bugfixes
=> config: clean and expand lnd tls cert path

frdrpcserver/macaroons.go, frdrpcserver/perms/perms.go
This commit moves the RequiredPermissions map to its own directory so
that projects importing the permissions list dont need to import all the
dependencies of the frdrpcserver package.
=> frdrpcserver: move RequiredPermissions to dedicated dir

fiat/coingecko.go, fiat/coingecko_test.go, fiat/prices.go, fiat/prices_test.go, tools/Dockerfile
The coingecko API automatically changes its granularity depending on how old is the pricing data you are asking for. For 90 days or less, it returns hourly entries while for any date 91 days or older it returns daily granularity.
To obtain the most exact results we should always make any reports in that 90 days window. That's why we currently do not support ranges that include dates older than 90 days.
In some case it may make sense to use daily data. This commit extends the current API to adapt the range and ensure that we get always the best possible data.
=> fiat: add support fo multiple granularities to coingecko

README.md, itest/test_context.go, itest/util.sh
Updates the README to document what permissions Faraday requires in a custom scoped `lnd` macaroon.
Also updates the integration test to verify those scoped permissions.
=> Document scoped lnd macaroon for Faraday

accounting/entries.go, accounting/entries_test.go, accounting/filter.go, accounting/filter_test.go, accounting/off_chain_test.go
Include invoice memo in audit nodes for outgoing payments that pay to an invoice. This allows for more options to correlate money movements during reconciliation.
Context: Improves ability to reconcile payments related to peerswaps. See https://github.com/ElementsProject/peerswap/issues/254 for additional context.
This pull request involves changes to the `accounting` package, specifically the `entries.go`, `entries_test.go`, `filter.go`, and `filter_test.go` files. The changes primarily involve the addition of a `description` field to the `paymentInfo` struct and the modification of the `paymentNote` function to include the `memo` field. The changes also involve modifications to the `paymentEntry` and `paymentRequestDetails` functions to accommodate the new `description` field.
Fix …
=> Include outgoing payment description in audit memo

config.go
Fixes https://github.com/lightninglabs/faraday/issues/184
This pull request includes changes to the `config.go` file that primarily focus on renaming and reusing the `DefaultAutogenValidity` constant as `defaultTLSCertDuration` and `TLSCertDuration`. The changes allow for the duration of the auto-generated TLS certificate to be customized.
Here are the key changes:
* Renamed `DefaultAutogenValidity` to `defaultTLSCertDuration` and updated its comment to reflect the new name.
* Added `TLSCertDuration` in the `Config` struct, which allows the user to set the duration for the auto-generated TLS certificate.
* Set `TLSCertDuration` to `defaultTLSCertDuration` in the `DefaultConfig` function.
* Replaced `DefaultAutogenValidity` with `cfg.TLSCertDuration` in the `loadCertWithCreate` function, …
=> config: allow tls cert validity duration to be configured

config.go
Is there anything more than this needed to enable signet support?
Fixes #132
=> config: add support for signet

frdrpcserver/rpcserver.go
- Related issue: [#177 ResourceExhausted error while running the Node Audit](https://github.com/lightninglabs/faraday/issues/177)
The change for this PR increases the gRPC message size limit from 400MiB to 600MiB.  We encountered a ResourceExhausted error while running the NodeAudit report, particularly on nodes with a high number of on-chain transactions.
```
{'code': 8, 'message': 'grpc: received message larger than max (419942095 vs. 419430400)', 'details': []}
```
This error could be  due to the gRPC message size exceeding the current 400MiB limit. In LND, this limit is configurable and can be adjusted by the calling client, but Faraday currently lacks this configurability.  This is a temporary fix, with issue 177 recommending a long-term solution involving the implementation of …
=> frdrpcserver: update rpcserver-max-recv-size

docs/accounting.md
The changes [here](https://github.com/lightninglabs/docs.lightning.engineering/pull/723) were overwritten because they need to be applied to the synced doc directly.
While editing the doc I also fixed some other stuff.
=> docs: formatting and typos/grammar

.github/workflows/docker.yml
- Closes #175 
To validate the effectiveness of the newly integrated GitHub Action for automating Docker image pushes to Docker Hub upon a new release, follow these steps:
1. Trigger a New Release:
Navigate to the repository's 'Releases' section.
Create a new release. You can do this by tagging a specific commit or using the repository's latest commit. Ensure that the release process mimics the standard release procedure for this repository.
2.Verify GitHub Action Execution:
Once the release is created, go to the 'Actions' tab in the GitHub repository.
You should see a new workflow run initiated by the release action. This workflow corresponds to the GitHub Action we have added for Docker image automation.
3. Check Workflow Logs:
Click on the workflow run to view its details.
Review the …
=> chore: adds github actions to push faraday docker images to docker hub

fiat/coinbase_api.go, fiat/prices.go, fiat/prices_test.go, go.mod, go.sum, version.go
With this commit we add Coinbase to the existing fiat sources.
=> fiat: add support for using Coinbase to fetch hourly/daily prices
